### PR TITLE
Rewrite codegen

### PR DESCRIPTION
**Pull request by david-zk**
Rewritie of codegen in typescript, I regenerated differences for `lib/Impl.sol` file, it is mainly comment/whitespace changes which shouldn't have semantic meaning.

I run codegen like `npx ts-node codegen/main.ts && npm run prettier testgen/Impl.sol`

Renerated files:
Impl.sol
Common.sol
Precompiles.sol
TFHE.sol

@tremblaythibaultl @immortal-tofu

### CODE REVIEW

**Comment by aquint-zama** [comment]
@cla-bot check

**Review by tremblaythibaultl — APPROVED** [review]
lgtm 👍

**Review by immortal-tofu — APPROVED** [review]
Good job!

**Comment by immortal-tofu** [comment]
lgtm 👍 
Just, can you run prettier on the code before merging (if it's not already prettier-ified) ?

**Comment by david-zk** [comment]
> lgtm 👍 Just, can you run prettier on the code before merging (if it's not already prettier-ified) ?

Prettify already ran here

**Pull request merged**
