### PR TITLE
feat: introduce select in place of cmux

### PR DESCRIPTION
**Pull request by immortal-tofu**

### CODE REVIEW

**Comment by jatZama** [comment]
Can you run the codegen before merging? there is still no select in the TFHE library. Also please update the tests.

**Review by jatZama — COMMENTED** [review]
Can you run the codegen before merging?

**Review by jatZama — COMMENTED** [review]
Ok for me but the async decrypt oracle test might fail probably because the codehash of the predploy would have changed.

**Comment by immortal-tofu** [comment]
> Ok for me but the async decrypt oracle test might fail probably because the codehash of the predploy would have changed.

We'll need to update it

**Review by jatZama — APPROVED** [review]

**Pull request merged**
