### PR TITLE
Add regression

### PR DESCRIPTION
**Pull request by david-zk**
Adds regression test

@jatZama

### CODE REVIEW

**Comment by immortal-tofu** [comment]
Is it still relevant @david-zk ?

**Comment by jatZama** [comment]
This was an example of transaction without any FHE computation (from an issue found by Shiba, but I also found similar issues few times) which failed on fhevm due to wrong gas estimation. @dartdart26 asked me about it few days ago, something to keep in mind because this kind of failure is not expected at all.

**Comment by immortal-tofu** [comment]
Can we close this PR @jatZama ?

**Comment by jatZama** [comment]
You can close if you want, since this Regression test is already present here, so we can keep track of it since ethermint still has issues in gas estimation: https://github.com/zama-ai/fhevm/blob/main/examples/Regression1.sol
For the moment it is "solved" by overriding gasLimit by +20% of original value in the extended provider here https://github.com/zama-ai/fhevm/blob/main/CustomProvider.ts#L19 
Note that this trick does not solve the gas estimation error we get in the async decrypt tests however, so in those we are still using a hardcoded gasLimit in ethermint as you can see here: https://github.com/zama-ai/fhevm/blob/main/test/gatewayDecrypt/testAsyncDecrypt.ts#L22

**Pull request closed without merging**
