### PR TITLE
docs: mention in the doc limited support during the EOY break

### PR DESCRIPTION
**Pull request by bcm-at-zama**
We want to mention that during the end of the year, the support for our sepolia testnet is very limited. Once merged, I made a PR to revert, that we'll merge early jan.

### CODE REVIEW

**Comment by bcm-at-zama** [comment]
My first PR in here, I don't know if we build GB preview on the branch

**Comment by bcm-at-zama** [comment]
yes there is a preview, great

**Comment by yuxizama** [comment]
Looks good to me. Thank you!
Maybe @immortal-tofu could verify the wording?

**Review by yuxizama — APPROVED** [review]

**Review by immortal-tofu — APPROVED** [review]

**Comment by bcm-at-zama** [comment]
@immortal-tofu I don't know how you proceed in fhEVM team, ie if I have to merge or if you do it yourself.

**Comment by bcm-at-zama** [comment]
finally I wonder if there is an issue with #667: in https://docs.zama.ai/fhevm, we show the GB doc of 0.6, not of main. I am not sure doing a commit in a release branch is that great. So, a banner would really be simpler

So, finally, not sure we should merge, or merge as is

**Pull request closed without merging**
